graph LR
    linguists --1.00--> theologians
    theologians --1.00--> linguists
    runes --1.00--> writings
    linguist -.-> writings
    theologians -.-> interpretations
    interpretations --0.12--> doctrine
    theologians -.-> doctrine
    energy --0.33--> recons
    interpretations --0.33--> doctrine
    theologians -.-> doctrine
    linguists -.-> doctrine
    minerals --0.75--> fighters
    minerals --0.20--> destroyers
    minerals --0.50--> fighters
    minerals --0.60--> fighters
    managers -.-> fighters
    managers -.-> fighters
    energy --0.40--> linguist
    energy --0.33--> theologians
    writings --1.20--> interpretations
    interpretations --1.33--> interpretations
    energy --0.33--> cars
    minerals --4.00--> energy
    cars --2.00--> energy
    energy --1.50--> soldiers
    energy --0.33--> officers
    officers -.-> soldiers
    energy --0.67--> officers
     --0.50--> recons
    energy --0.20--> recons
    officers -.-> recons
    fighters -.-> recons
    energy --0.33--> vulnerabilities
    officers -.-> vulnerabilities
    managers -.-> vulnerabilities
    workers --2.00--> minerals
    energy --0.20--> minerals
    energy --0.25--> minerals
    energy --0.33--> minerals
    workers --1.00--> managers
    managers -.-> minerals
    managers -.-> managers
    energy --0.50--> minerals
    workers -.-> minerals
    energy --0.50--> engineers
    energy --0.60--> engineers
    energy --0.50--> workers
    energy --0.50--> managers
    officers -.-> vulnerabilities
    linguists -.-> vulnerabilities
    soldiers -.-> fighters
    soldiers -.-> destroyers
    officers -.-> fighters
    officers -.-> destroyers
