graph LR
    energy --0.33--> cars
    energy --0.50--> engineers
    energy --0.60--> engineers
    energy --0.50--> workers
    energy --0.50--> managers
    officers -.-> soldiers
    energy --1.50--> soldiers
    energy --0.33--> officers
    energy --0.67--> officers
    soldiers -.-> fighters
    soldiers -.-> destroyers
    officers -.-> fighters
    officers -.-> destroyers
    energy --0.40--> linguist
    energy --0.33--> theologian
    energy --0.50--> engineers
    energy --1.50--> workers
    workers --0.50--> minerals
    energy --0.20--> minerals
    minerals --0.50--> fighters
    minerals --0.60--> fighters
    managers -.-> fighters
    managers -.-> fighters
    energy --0.25--> minerals
    energy --0.33--> minerals
    workers --1.00--> managers
    managers -.-> minerals
    managers -.-> managers
    minerals --0.75--> fighters
    minerals --0.20--> destroyers
    minerals --6.00--> energy
    cars --4.00--> energy
